name: profit_grocery_application
description: "A mobile e-commerce application for online grocery shopping with coupon-based offers."
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  dartz: ^0.10.1
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_database: ^11.3.5
  firebase_remote_config: ^5.4.3
  firebase_analytics: ^11.4.1
  http: ^1.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  crypto: ^3.0.3
  change_app_package_name: ^1.5.0
  rename: ^3.0.2
  sendotp_flutter_sdk: ^0.0.1
  uuid: ^4.3.3  # Still needed for address ID generation in profile/address_form_page.dart
  connectivity_plus: ^5.0.2
  razorpay_flutter: ^1.4.0
  fluttertoast: ^8.2.12
  # sendotp_flutter_sdk: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/categories/
    - assets/subcategories/
    - assets/products/
    - assets/cimgs/
    - assets/icon/res/mipmap-xxxhdpi/ic_launcher.png
    - assets/icon/res/mipmap-xxxhdpi/ic_launcher_background.png
    - assets/icon/res/mipmap-xxxhdpi/ic_launcher_foreground.png
    - assets/icon/play_store_512.png

  # Add custom fonts later if required
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700

flutter_icons:
  android: true
  image_path: "assets/icon/res/mipmap-xxxhdpi/ic_launcher.png"
  adaptive_icon_background: "assets/icon/res/mipmap-xxxhdpi/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/icon/res/mipmap-xxxhdpi/ic_launcher_foreground.png"
  # min_sdk_android: 21