name: profit_grocery_application
description: "A mobile e-commerce application for online grocery shopping with coupon-based offers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  dartz: ^0.10.1
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_database: ^11.3.5
  firebase_remote_config: ^5.4.3
  http: ^1.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  change_app_package_name: ^1.5.0
  rename: ^3.0.2
  sendotp_flutter_sdk: ^0.0.1
  # sendotp_flutter_sdk: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/categories/
    - assets/subcategories/
    - assets/products/
    - assets/cimgs/

  # Add custom fonts later if required
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
